"""Add unique recipe constraint

Revision ID: 7c573af2cff3
Revises: 9fc4781a1d30
Create Date: 2024-01-05 08:58:23.606546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c573af2cff3'
down_revision = '9fc4781a1d30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
