"""Unique session topic

Revision ID: 832a852781cc
Revises: 
Create Date: 2023-12-08 16:19:07.095583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832a852781cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
