"""Revise chat session model

Revision ID: c47d4c55e8dd
Revises: 832a852781cc
Create Date: 2023-12-14 12:53:02.436945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47d4c55e8dd'
down_revision = '832a852781cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('topic', table_name='chat_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('topic', 'chat_sessions', ['topic'], unique=False)
    # ### end Alembic commands ###
